minecraft:
  serviceAnnotations:
    mc-router.itzg.me/externalServerName: "vanilla.4amlunch.net"

  resources:
    requests:
      cpu: 250m

  minecraftServer:
    eula: "TRUE"
    version: "1.19.3"
    type: "VANILLA"
    difficulty: normal
    whitelist:
      - BlockyJackBauer
      - io42
    ops:
      - BlockyJackBauer
    maxWorldSize: 60000
    enableCommandBlock: false
    forcegameMode: true
    motd: "Welcome to Vanilla on Kubernetes!"
    memory: 4G

    rcon:
      enabled: true
      port: 25575
      existingSecret: minecraft-server
      secretKey: rcon-password
      serviceType: ClusterIP

  persistence:
    storageClass: "ceph-block"
    dataDir:
      enabled: true
      Size: 25Gi

  mcbackup:
    enabled: true
    destDir: /backups
    persistence:
      storageClass: "ceph-block"
      backupDir:
        enabled: true
        Size: 100Gi
