minecraft:
  serviceAnnotations:
    mc-router.itzg.me/externalServerName: "vanilla.4amlunch.net"

  minecraftServer:
    eula: "TRUE"
    version: "1.19.3"
    type: "VANILLA"
#    forgeVersion: "40.1.80"
#    packwizURL: "https://mc.4amlunch.net/packs/TerraFirmaCreate/pack.toml"
    difficulty: normal
#    levelType: "tfc:tng"
    whitelist:
      - BlockyJackBauer
      - io42
    ops:
      - BlockyJackBauer
    maxWorldSize: 60000
    enableCommandBlock: false
    forcegameMode: true
    motd: "Welcome to Vanilla on Kubernetes!"
    memory: 4G

    rcon:
      enabled: true
      port: 25575
      existingSecret: minecraft-server
      secretKey: rcon-password
      serviceType: ClusterIP

    persistence:
      storageClass: "ceph-block"
      dataDir:
        enabled: trua
        Size: 10Gi

    mcbackup:
      enabled: true
      destDir: /backups
      persistence:
        storageClass: "ceph-filesystem"
        backupDir:
          enabled: enabled
          Size: 100Gi
