chartmuseum:
  env:
    existingSecret: chartmuseum-secret
    existingSecretMappings:
      BASIC_AUTH_USER: basic-auth-user
      BASIC_AUTH_PASS: basic-auth-pass
#      CACHE_REDIS_PASSWORD: redis-password
    open:
      STORAGE: local
      DISABLE_API: false
      AUTH_ANONYMOUS_GET: true
      CACHE: redis
      CACHE_REDIS_ADDR: redis-shared-leader.datalake.svc.cluster.local
      CACHE_REDIS_DB: 0
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 100Gi
    storageClass: ssd-large
  ingress:
    enabled: true
    hosts:
      - name: charts.4amlunch.net
        pathType: ImplentationSpecific
