groundcover:
  global:
    groundcoverPredefinedTokenSecret:
      secretName: groundcover-vars
      secretKey: token
  rbac:
    pspEnabled: false

  victoria-metrics-single:
    server:
      persistentVolume:
        storageClass: ceph-block
    rbac:
      pspEnabled: false

  victoria-metrics-agent:
    rbac:
      pspEnabled: false

  timescaledb-single:
    secrets:
      credentialsSevretName: timescaledb-vars
    persistentVolumes:
      data:
        storageClass: ceph-block
      wal:
        storageClass: ceph-block
    rbac:
      pspEnabled: false

  loki:
    persistence:
      storageClassName: ceph-block
    rbac:
      pspEnabled: false

