prometheus:
  grafana:

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - grafana.4amlunch.net

    persistence:
      storageClassName: "ssd"
