traefik:
  additionalArguments:
    - --entrypoints.websecure.http.tls.certresolver=cloudflare
    - --entrypoints.websecure.http.tls.domains[0].main=4amlunch.net
    - --entrypoints.websecure.http.tls.domains[0].sans=*.4amlunch.net
    - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
    - --certificatesresolvers.cloudflare.acme.email=wonko@4amlunch.net
    - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
    - --certificatesresolvers.cloudflare.acme.storage=/certs/acme.json

  ports:
    web:
      redirectTo:
        port: websecure

  env:
    - name: CF_API_EMAIL
      valueFrom:
        secretKeyRef:
          key: email
          name: cloudflare-api-credentials
    - name: CF_API_KEY
      valueFrom:
        secretKeyRef:
          key: apiKey
          name: cloudflare-api-credentials

  ingressRoute:
    dashboard:
      enabled: false

  persistence:
    enabled: true
    path: /certs
    size: 128Mi
    storageClass: ssd
