alliance-auth:
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 1Gi

  auth:
    sitename: "A Band Apart (SUPERDEV)"
    protocol: "https"
    subdomain: "aa-dev"
    domain: "4amlunch.net"
    debug: False
    existingSecret: fouram-dev-auth-secret
    # secret contains a key named "secretKey"

  db:
    name: "alliance_auth_4am_dev"
    host: moco-shared-primary.datalake.svc.cluster.local
    port: 3306
    existingSecret: fouram-dev-db-secret
    # secret contains the keys "username" and "password"

  redis:
    host: redis-shared-leader.datalake.svc.cluster.local
    port: 6379
    existingSecret: aba-prod-redis-secret
    db: 1

  email:
    host: mail.gandi.net
    port: 587
    useTLS: true
    defaultFrom: no-reply@aba-eve.com
    existingSecret: fouram-dev-email-secret
    # secret contains the keys "username" and "password"

  esi:
    email: "wonko@4amlunch.net"
    existingSecret: fouram-dev-esi-secret
    # secret contains they keys "clientId" and "clientSecret"

  celery:
    workers: 2

  volumes:
    static:
      storageClass: ssd

  services:
    discord:
      enabled: true
      existingSecret: fouram-dev-discord-secret
      guildId: "374983726763081738"
      syncName: False
    autogroups:
      enabled: true
    eveuniverse:
      enabled: true
    structures:
      enabled: true
    structuretimers:
      enabled: true
    fittings:
      enabled: true
    mailrelay:
      enabled: true
    killtracker:
      enabled: true
    moonmining:
      enabled: true
    memberaudit:
      enabled: true
    aa_rss_to_discord:
      enabled: true
    discordproxy:
      enabled: true
      existingSecret: fouram-dev-discord-secret
    discordbot:
      enabled: true
      cogs:
        sov: false
    blueprints:
      enabled: true
    marketmanager:
      enabled: true
    securegroups:
      enabled: true
    buybackprogram:
      enabled: true
    standingsrequests:
      enabled: true
      STANDINGS_API_CHARID: "242537709"
      STR_ALLIANCE_IDS:
        - "99004295"
    taskmonitor:
      enabled: true
    celeryanalytics:
      enabled: true
