minecraft:
  image:
    pullPolicy: Always

  extraVolumes:
    - volumeMounts:
      - name: modpacks
        mountPath: /modpacks
        readOnly: true
        subPath: packs
    - volumes:
      - name: modpacks
        persistentVolumeClaim:
          claimName: minecraft-web

  resources:
    requests:
      cpu: 250m

  serviceAnnotations:
    mc-router.itzg.me/externalServerName: "alexsworld.4amlunch.net"

  extraEnv:
    EXISTING_WHITELIST_FILE: SYNCHRONIZE
    EXISTING_OPS_FILE: SYNCHRONIZE

  minecraftServer:
    eula: "TRUE"
    version: "1.20.1"
    type: "FORGE"
    forgeVersion: "47.2.0"
    packwizURL: "https://mc.4amlunch.net/packs/alexs-world/pack.toml"
    difficulty: normal
    levelType: DEFAULT
    whitelist: BlockyJackBauer,io42,SuperSammyDino,BennyPlayerX
    ops: BlockyJackBauer
    maxWorldSize: 60000
    enableCommandBlock: false
    forcegameMode: true
    motd: "Welcome to Alex's World!"
    memory: 4G

    rcon:
      enabled: true
      port: 25575
      existingSecret: minecraft-server
      secretKey: rcon-password
      serviceType: ClusterIP

  persistence:
    storageClass: "ceph-block"
    dataDir:
      enabled: true
      Size: 25Gi

  mcbackup:
    enabled: true
    destDir: /backups
    resources:
      requests:
        cpu: 250m
    persistence:
      storageClass: "ceph-block"
      backupDir:
        enabled: true
        Size: 100Gi
